# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["dora@kalneus.com"]
description = "Passkey implementation with WebAuthn and Fastly Compute"
language = "rust"
manifest_version = 2
name = "compute-rust-passkey"
service_id = "xnlmrqP8ip48pdXb9Vpbd3"

[local_server]

  [local_server.backends]

  [local_server.kv_stores]

    [[local_server.kv_stores.keys]]
      data = "[]"
      key = "test"

    [[local_server.kv_stores.state]]
      data = "[]"
      key = "test"

    [[local_server.kv_stores.users]]
      data = "[]"
      key = "test"

[scripts]
  build = "cargo build --bin compute-rust-passkey --release --target wasm32-wasi --color always"
